// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrlbjertrcqijmkjcwyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybGJqZXJ0cmNxaWpta2pjd3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzExNjMsImV4cCI6MjA3NDIwNzE2M30.GsnW6L9Xf4uTgP-SFkQLfbzKZcKvmfoNd6_WYGcAhIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});